# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0002_remove_pdf_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='contributors',
            field=models.ManyToManyField(default=1, related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
