# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import pdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_auto_20180216_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=pdf.models.upload_location),
        ),
    ]
