# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_notification_is_reverted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='need_response',
            field=models.BooleanField(default=True),
        ),
    ]
