# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_notification_need_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('IU', 'Invite'), ('AI', 'Accepted Invitation'), ('AU', 'Accepted Update'), ('UU', 'Uploaded Update')], max_length=2),
        ),
    ]
